---
language: [ ruby, node_js ]
rvm: [ 2.2.1 ]
node_js: [ 0.12 ]
cache:
  bundler: true
  directories:
    - bower_components
sudo: false

before_script:
  - npm install -g bower
  - bower install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the first command below with the generated one.
before_install:
  - openssl aes-256-cbc -K $encrypted_843694bda23e_key -iv $encrypted_843694bda23e_iv -in .deploy_key.enc -out .deploy_key -d
  - eval "$(ssh-agent)"
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

# Set the branch that will be built and published to GitHub pages.
branches:
  only:
    - master

# Run the command below (fill in your name and email):
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com'
# Replace the value of secure with your generated value.
env:
  - secure: "cRDoABRbxpJotZP5iGegUXbfDtxRWJaXS2qDyW7K0o/tDs7bgeRUvN1MspuGEZVWs1mPwNsen7CXUBMjl7YhaMW6P2Gj/0TWSOvYVyWSEb5xvvVUxYjJEIJlVfEogzMFqk18OdWM0vdeWRNwQczrnSJKvkcXVyeLpqJ0nIMzkm8="
